server:
  port: 32772

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:32771/eureka/
  instance:
    prefer-ip-address: 'true'

logging:
  org.springframework.cloud.gateway: DEBUG
  reactor.netty.http.client: DEBUG
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"


spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**
          filters:
            - RewritePath=/employee/(?<path>.*), /$\{path}
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/department/**
          filters:
            - RewritePath=/department/(?<path>.*), /$\{path}
        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/org/**
          filters:
            - RewritePath=/org/(?<path>.*), /$\{path}
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}
        - id: correspondence-service
          uri: lb://correspondence-service
          predicates:
            - Path=/correspond/**
          filters:
            - RewritePath=/correspond/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: employee
        url: /v3/api-docs/employee
      - name: department
        url: /v3/api-docs/department
      - name: organization
        url: /v3/api-docs/organization
      - name: auth
        url: /v3/api-docs/auth
      - name: correspond
        url: /v3/api-docs/correspond


management:
  tracing:
    sampling:
      probability: 1.0

  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
      external-file: ../logs/client.log