server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/
    healthcheck:
      enabled: true
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: gloomme.crater365.organization

spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/crater365-organizations
    username: root
    password: ''

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans